# Use container based faster infra
sudo: false

language: c

compiler:
  - gcc
  - clang

cache:
  directories:
  - download-cache

# Test with multiple Nginx versions
# Source: http://nginx.org/en/download.html
env:
  - NGINX_VERSION=1.13.2
  - NGINX_VERSION=1.13.0
  - NGINX_VERSION=1.12.0 
  - NGINX_VERSION=1.10.3

install:
  # Use cache folder
  - if [ ! -d download-cache ]; then mkdir download-cache; fi

  # Install nginx
  - if [ ! -f download-cache/nginx-$NGINX_VERSION.tar.gz ]; then wget -O download-cache/nginx-$NGINX_VERSION.tar.gz http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz; fi

  - tar zxf download-cache/nginx-$NGINX_VERSION.tar.gz
  - mv nginx-$NGINX_VERSION nginx
  
  # Agree to the stuff that cpan is asking in it's initial install
  - echo "\n" | cpan

  # Install needed perl modules
  - cpan install Redis local::lib Test::More
  
  # Build nginx with this module
  - cd nginx
  - ./configure --prefix=/etc/nginx --add-module=$(realpath ..)

  # Use all cores available in the builds with -j${NPROC} flag
  - readonly NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1)  && \
    
    # Build Nginx
  - make -j${NPROC}
  - make -j${NPROC} install

  - cd ..

script:

  # Run tests
  - prove -r t