# Use docker to run the tests
sudo: required

language: c

services:
  - docker

# Test with multiple Nginx versions
# Source: http://nginx.org/en/download.html
env:
  matrix:
    # Alpine uses musl c library
    - NGINX_VERSION=1.9.15 BUILD_DISTRO=alpine COMPILER=gcc
    - NGINX_VERSION=1.11.2 BUILD_DISTRO=alpine COMPILER=gcc

    # Debian uses glibc c library run with GNU C compiler
    - NGINX_VERSION=1.9.15 BUILD_DISTRO=debian COMPILER=gcc
    - NGINX_VERSION=1.11.2 BUILD_DISTRO=debian COMPILER=gcc
    
    # Run also with clang compiler
    - NGINX_VERSION=1.9.15 BUILD_DISTRO=debian COMPILER=clang
    - NGINX_VERSION=1.11.2 BUILD_DISTRO=debian COMPILER=clang

script:
  # Installs all dependencies in a alpine linux container and runs the tests
  - docker build -f test-$BUILD_DISTRO.Dockerfile --build-arg NGINX_VERSION=$NGINX_VERSION --build-arg CC=$COMPILER .