# Use container based faster infra
sudo: required
dist: trusty

language: c

compiler:
  - gcc
  - clang

cache:
  directories:
  - download-cache

# Test with multiple Nginx versions
# Source: http://nginx.org/en/download.html
env:
  - NGINX_VERSION=1.13.2
  - NGINX_VERSION=1.12.0
  - NGINX_VERSION=1.9.15

install:
  # Use cache folder
  - if [ ! -d download-cache ]; then mkdir download-cache; fi

  # Install nginx
  - if [ ! -f download-cache/nginx-$NGINX_VERSION.tar.gz ]; then wget -O download-cache/nginx-$NGINX_VERSION.tar.gz http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz; fi

  - tar zxf download-cache/nginx-$NGINX_VERSION.tar.gz
  - mv nginx-$NGINX_VERSION nginx
  
  # Install cpanm
  - sudo apt-get install -qq -y cpanminus axel

  # Install needed perl modules
  - sudo cpanm --quiet --installdeps --notest ./t/ > build.log 2>&1 || (cat build.log && exit 1)
  
  # Build nginx with this module
  - cd nginx
  - ./configure --prefix=/etc/nginx --add-module=$(realpath ..)

  # Use all cores available in the builds with -j${NPROC} flag
  - readonly NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1)  && \
    
    # Build Nginx
  - make -j${NPROC}
  - make -j${NPROC} install

  - cd ..

script:

  # Run tests
  - prove -r t