# Use container based faster infra
sudo: required

services:
  - docker

# Test with multiple Nginx versions
# Source: http://nginx.org/en/download.html
env:
  - NGINX_VERSION=1.13.2
  - NGINX_VERSION=1.13.0
  - NGINX_VERSION=1.12.0 
  - NGINX_VERSION=1.10.3

script:
  # Installs all dependencies in a alpine linux container and runs the tests
  - docker build -f test-environment.Dockerfile --build-arg NGINX_VERSION=$NGINX_VERSION .